/*
 * Calculator API
 *
 * API for performing arithmetic operations
 *
 * OpenAPI spec version: 1.0.0
 *
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System.Runtime.Serialization;
using System.Text.Json.Serialization;

namespace IO.Swagger.Models.Math {

	/// <summary>
	/// Gets or Sets MathOperationType
	/// </summary>
	[JsonConverter(typeof(JsonStringEnumConverter))]
	public enum MathOperationType {
		/// <summary>
		/// Enum AddEnum for add
		/// </summary>
		[EnumMember(Value = "add")] Add = 0,
		/// <summary>
		/// Enum SubtractEnum for subtract
		/// </summary>
		[EnumMember(Value = "subtract")] Subtract = 1,
		/// <summary>
		/// Enum MultiplyEnum for multiply
		/// </summary>
		[EnumMember(Value = "multiply")] Multiply = 2,
		/// <summary>
		/// Enum DivideEnum for divide
		/// </summary>
		[EnumMember(Value = "divide")] Divide = 3
	}
}
